version: '2.1.12'
services:
  config:
    build:
      dockerfile: './config.dockerfile'
    ports:
      - '8054:8054'

  users:
    build:
      dockerfile: './users.dockerfile'
    depends_on:
      config:
        condition: service_healthy
    
    ports:
      - '8080:8080'

  jokes:
    build:
      dockerfile: './jokes.dockerfile'
    depends_on:
      config:
        condition: service_healthy
    ports:
      - '8055:8055'
  
  ratings:
    build:
      dockerfile: './ratings.dockerfile'
    depends_on:
      config:
        condition: service_healthy
    ports:
      - '8056:8056'

networks:
  default:
    driver: bridge
      